# Base blog settings
baseurl                      : ''
url                          : 'https://minicomp.github.io'

blog:
  title                      : Minicomp
  description                : ''
  logo_path                  : '/assets/img/logo2.svg'
  search_path                : ''
  hero_layout                : true
  hero_placeholder           : '/assets/img/branch.jpg'
  excerpts                   : true
  inline_footnotes           : true
  titles_only                : false

# Fonts
  font                       : "Rubik', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif"
  load_google_fonts          : 'Rubik:400,400italic,700,700italic'

# Author info
author:
  github                    : minicomp
  gitter                    : minicomp
  fullname                  : Marii Nyröp
  rss                       : false



## Advanced blog settings

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate                     : 5
paginate_path                : '/page-:num/'

# Permalinks
permalink                    : notes/:slug

# Posts
excerpt_separator            : <!–-break-–>

# Tags
collections:
  tags:
    output: true
    permalink: /tag/:slug
  projects:
    output: true
    permalink: /projects/:slug
defaults:
  -
    scope:
      path: ''
      type: my_tags
    values:
      layout: blog-by-tag

sass:
  sass_dir                : _scss
  style                   : compressed
